### ISSUE TITLE
Pulser DAC offset correction is not loaded from text file

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/pyBAR#2]
After running a PlsrDacOffset calibration scan the offsets per DC are stored in the configuration.cfg. To read these back to a list fails. Mlst likely the text file parsing has to be fixed.

**Comment by lauramari** [comment]
After baseline tuning & pulser dac offset calibration, the tune feedback scan  returns the following error below.

Traceback (most recent call last):
  File "c:\users\student\git\pybar\host\pybar\run_manager.py", line 107, in run
    self._run()
  File "c:\users\student\git\pybar\host\pybar\fei4_run_base.py", line 201, in _run
    self.scan()
  File "C:\Users\student\git\pyBAR\host\pybar\scans\tune_feedback.py", line 87, in scan
    scan_loop(self, cal_lvl1_command, repeat_command=self.n_injections_feedback, mask_steps=mask_steps, enable_mask_steps=enable_mask_steps, enable_double_columns=None, same_mask_for_all_dc=True, eol_function=None, digital_injection=False, enable_shift_masks=self.enable_shift_masks, disable_shift_masks=self.disable_shift_masks, restore_shift_masks=True, mask=None, double_column_correction=self.pulser_dac_correction)
  File "c:\users\student\git\pybar\host\pybar\fei4\register_utils.py", line 962, in scan_loop
    dc_address_command = get_dc_address_command(enable_double_columns[0])
  File "c:\users\student\git\pybar\host\pybar\fei4\register_utils.py", line 883, in get_dc_address_command
    self.register.set_global_register_value("PlsrDAC", initial_plsr_dac + plsr_dac_correction[dc])
  File "c:\users\student\git\pybar\host\pybar\fei4\register.py", line 589, in set_global_register_value
    value = long(str(value), 0)  # value is decimal string or number or BitVector
ValueError: invalid literal for long() with base 10: '284.339486296'
