### ISSUE TITLE
Crash in analysis for cluster plots and no hits in data

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/pyBAR#77]
```bash
Traceback (most recent call last):
  File "/home/davidlp/git/Thesis/Analysis/Simulation/X_ray_calib/fei4_tdc_analysis.py", line 59, in <module>
    analyze_hits(file_name)
  File "/home/davidlp/git/Thesis/Analysis/Simulation/X_ray_calib/fei4_tdc_analysis.py", line 26, in analyze_hits
    :-3], analyzed_data_file=input_file_hits[:-3] + '_analyzed.h5')
  File "/home/davidlp/git/pyBAR/pybar/analysis/analyze_raw_data.py", line 1229, in plot_histograms
    plotting.plot_cluster_size(hist=out_file_h5.root.HistClusterSize if out_file_h5 is not None else self.cluster_size_hist, filename=output_pdf)
  File "/home/davidlp/miniconda2/lib/python2.7/site-packages/tables/group.py", line 818, in __getattr__
    return self._f_get_child(name)
  File "/home/davidlp/miniconda2/lib/python2.7/site-packages/tables/group.py", line 698, in _f_get_child
    self._g_check_has_child(childname)
  File "/home/davidlp/miniconda2/lib/python2.7/site-packages/tables/group.py", line 395, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``HistClusterSize``
```

**Comment by laborleben** [comment]
Fixed.
